// flow-typed signature: 190a9347d079351229fbf66985c2b133
// flow-typed version: <<STUB>>/less-plugin-autoprefix_v^1.5.1/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-plugin-autoprefix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-plugin-autoprefix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less-plugin-autoprefix/lib/autoprefix-processor' {
  declare module.exports: any;
}

declare module 'less-plugin-autoprefix/lib/index' {
  declare module.exports: any;
}

declare module 'less-plugin-autoprefix/lib/parse-options' {
  declare module.exports: any;
}

declare module 'less-plugin-autoprefix/lib/usage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less-plugin-autoprefix/lib/autoprefix-processor.js' {
  declare module.exports: $Exports<'less-plugin-autoprefix/lib/autoprefix-processor'>;
}
declare module 'less-plugin-autoprefix/lib/index.js' {
  declare module.exports: $Exports<'less-plugin-autoprefix/lib/index'>;
}
declare module 'less-plugin-autoprefix/lib/parse-options.js' {
  declare module.exports: $Exports<'less-plugin-autoprefix/lib/parse-options'>;
}
declare module 'less-plugin-autoprefix/lib/usage.js' {
  declare module.exports: $Exports<'less-plugin-autoprefix/lib/usage'>;
}
